### ISSUE TITLE
Can you link the other skin packs?

### ISSUE THREAD

**Issue by Jun10rStud10s** [Permdog99/Legacy-Skin-Packs#2]
on the Modrinth page for it, it shows a table, on this table are some skin packs that have "been made as a Mash up by someone else", could you send links to these?

- Thanks in advance, JJ

**Comment by Pigzone00** [comment]
If you press the blue X, the link will open, though some packs are not in modrinth yet

**Comment by Jun10rStud10s** [comment]
what about the non modrinth ones?

**Comment by Pigzone00** [comment]
There aren't any non modrinth ones?

**Comment by Pigzone00** [comment]
There is one from discord, the mario skin pack, which I've updated

**Comment by Jun10rStud10s** [comment]
alright

**Comment by ThugShaker3D** [comment]
lmao
